import { IsString, IsOptional, IsIn, IsObject } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class TrackPageViewDto {
  @ApiProperty({
    example: 'sess_abc123',
    description: 'Anonymous session ID generated by the frontend',
  })
  @IsString()
  sessionId: string;

  @ApiProperty({ example: '/', description: 'Page path' })
  @IsString()
  path: string;

  @ApiPropertyOptional({ example: 'https://linkedin.com' })
  @IsOptional()
  @IsString()
  referrer?: string;

  @ApiPropertyOptional({ example: 'desktop' })
  @IsOptional()
  @IsIn(['mobile', 'tablet', 'desktop'])
  device?: string;
}

export class TrackEventDto {
  @ApiProperty({ example: 'sess_abc123' })
  @IsString()
  sessionId: string;

  @ApiProperty({
    example: 'section_view',
    description: 'Event type',
    enum: [
      'section_view',
      'chatbot_open',
      'chatbot_question',
      'contact_submit',
    ],
  })
  @IsIn(['section_view', 'chatbot_open', 'chatbot_question', 'contact_submit'])
  eventType: string;

  @ApiPropertyOptional({
    example: { section: 'work', question: 'What stack do you use?' },
    description: 'Any extra data relevant to the event',
  })
  @IsOptional()
  @IsObject()
  payload?: Record<string, any>;

  @ApiPropertyOptional({ example: 'desktop' })
  @IsOptional()
  @IsIn(['mobile', 'tablet', 'desktop'])
  device?: string;
}
